# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fav_themes',
            field=models.ManyToManyField(related_name='fav_users', to='themes.Theme'),
        ),
    ]
