# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('users', '0002_myuser_fav_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='like_images',
            field=models.ManyToManyField(related_name='like_users', to='images.ImagePost'),
        ),
    ]
