# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_like_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fav_themes',
            field=models.ManyToManyField(blank=True, related_name='fav_users', to='themes.Theme'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='like_images',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='images.ImagePost'),
        ),
    ]
