# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160604_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='weibo_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.TextField(default='deprecated!', max_length=100),
            preserve_default=False,
        ),
    ]
